# Generated by Django 3.2.8 on 2021-10-29 21:29

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderi'},
        ),
    ]
