# Generated by Django 3.2.8 on 2021-11-01 22:29

import apps.blog.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', null=True, upload_to=apps.blog.models.Post.handle_cover_file, verbose_name='Kapak'),
        ),
    ]
